before_install:
- "sudo apt-get update && sudo apt-get install --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra texlive-latex-recommended dvipng"
script:
- mkdir _build
- pdflatex -output-directory _build src/main.tex
deploy:
  provider: releases
  api_key:
    secure: VVr/JXM3k0aANQe3MG2Uo6acu7/hKgU22whfYgqTCPR38KJtn4nsQMj4FKGkkjT0FsORPAWGQ00H264T5vJlRCRaViLpcjOqhAkHUuA9uOud2TMBJKCvtQDBiNYI0epvkYwDE8vi5HTqbzeetTkU56gCjNLRZDDZpHsMg6/UOEc=
  file:
  - _build/Bachelorarbeit.pdf
  skip_cleanup: true
  on:
    tags: true