before_install:
- sudo apt-get install texlive-binaries
install:
- export PATH="$HOME/miniconda/bin:$PATH"
- if ! command -v conda > /dev/null; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  -O miniconda.sh; bash miniconda.sh -b -p $HOME/miniconda -u; conda config --add
  channels conda-forge; conda config --set always_yes yes; conda update --all; conda
  install tectonic; fi
- conda info -a
cache:
  directories:
  - "$HOME/miniconda"
  - "$HOME/.cache/Tectonic"
script:
- cd ./src/
- tectonic ./main.tex
#- makeindex ./main.idx
#- tectonic ./main.tex --print
- cd ../
deploy:
  provider: releases
  api_key:
    secure: h8ZD+jGsuk8sg2lhrRZ6jglJM/NCdthV7P+vEKJ+l7dByJRUHCEsvrKAd1gegUmtuHVjGvJ44dmCyg22KVc202Um7zQNPgY82gbgn1gRLBnOQ1dik4WpvHC+TivrMLjJpbSHnsj44K3NyB0HPQMRM0ayJ8dyNwLA63o2v/OaiFaQm5Vilyf3t3OXK0/t0hxKrYYgeGsywzHId8dO8rZ4VKXLO4UsQ0JTGSznFdlGqdGmWtguj5fFWCDBxY8hRXZMlrvA3sllcTx+2eWCe+sytaD3qExL95taOSdACzLmt/jkddk02AOe8v3cpB7VZUmnWRc6NsHLstVetaiOgYVSxenkUIXyVhnxp7i8rdSs/nfOTmHZQnZ5EUPG8a4BDjCbSoe1OdxzDxdM2XtqcX/dUsKDL5maEB9sPNlJpKFGLZXrrYTzpDp26j02xuRws4GfJICvUi3zFF+QJyTCPR/ACCD7wyywV5Wo+F3K1E+hLBPOyGg8Dyx4sQ6zzgIh6K+8J8UCNdRjort21S/Uv4Lad0q1pBsboMWRzivXlQH9vNkTyIMaTypb+d8UK7RgN3JYXKTlX+Ylw3dnqwwEa9iLq+nfa4CYBXn5XevSnEOCRPxT2fkEZB62xk6g4e4kHVDFqMEGMmRonMq8PLPquuftLFhAq2CgkqbR/frXGXJQ778=
  file: "./Bachelorarbeit.pdf"
  skip_cleanup: true
  on:
      branch: master
