before_install:
- "sudo apt-get update && sudo apt-get install --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra texlive-latex-recommended dvipng"
script:
- mkdir _build
- pdflatex -output-directory _build src/main.tex
deploy:
  provider: releases
  api_key:
    secure: H1Ru1C8fyJ+Ncj3d7ni4WnYhWeydkvdSxKUnE9VRqNnKpdUh9uTxZC3XLRyq6s+jFqyXAtAJ6V7RXiSaheuwkI7pm3ABmApombxsRrfYzA3Kiuguh+2J1tben0NsKCzwFCugbel3zTnze+PHwWOHW0CGpmwkNX0wXwz/lZoyhSw=
  file:
  - _build/Bachelorarbeit.pdf
  skip_cleanup: true
  on:
    tags: true